[*]
# global defaults, currently empty

[Qwen 3.8 27b dense]
model = ./models/web/Qwen3.8-27B-UD-Q8_K_XL.gguf
alias = Qwen 3.8
jinja = 1
# MTP stuff
spec-type = draft-mtp
spec-draft-n-max = 3
# brooke tweaks from AJ, copied to 3.8. Probably should test / tweak more.
ctx-size = 262144
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

[Qwen 3.6 27b dense]
model = ./models/web/Qwen3.6-27B-UD-Q8_K_XL.gguf
alias = Unsloth Quen3.6
jinja = 1
# Brooke tweaks from AJ
ctx-size = 262144
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

[unsloth/Qwen3-Coder-Next-GGUF:UD-Q4_K_XL]
jinja = 1
ctx-size = 32768
hf-repo = unsloth/Qwen3-Coder-Next-GGUF:UD-Q4_K_XL
alias = Unsloth Qwen3 UD Q4XL
#rope-scaling = yarn
#rope-scale = 4
#yarn-orig-ctx = 262144
n-gpu-layers = 33
#n-batch = 512
#n-ctx = 262144
no-kv-offload = 0

[unsloth/gpt-oss-20b-GGUF:F16]
jinja = 1
ctx-size = 32768
hf-repo = unsloth/gpt-oss-20b-GGUF:F16
alias = GPT-OSS 20b
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 3276

[Qwen/Qwen3-Coder-Next-GGUF:Q5_K_M]
jinja = 1
ctx-size = 262144
hf-repo = Qwen/Qwen3-Coder-Next-GGUF:Q5_K_M
alias = Qwen3-Coder-Next
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 262144
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 262144
no-kv-offload = 0

[ggml-org/gemma-3-1b-it-GGUF]
jinja = 1
ctx-size = 8192
hf-repo = ggml-org/gemma-3-1b-it-GGUF
alias = Gemma 3
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 8192