[unsloth/Qwen3-Coder-Next-GGUF:UD-Q4_K_XL]
jinja = 1
ctx-size = 262144
hf-repo = unsloth/Qwen3-Coder-Next-GGUF:UD-Q4_K_XL
alias = Unsloth Qwen3 UD Q4XL
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 262144
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 262144
no-kv-offload = 0

[unsloth/gpt-oss-20b-GGUF:F16]
jinja = 1
ctx-size = 32768
hf-repo = unsloth/gpt-oss-20b-GGUF:F16
alias = GPT-OSS 20b
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 3276

[Qwen/Qwen3-Coder-Next-GGUF:Q5_K_M]
jinja = 1
ctx-size = 262144
hf-repo = Qwen/Qwen3-Coder-Next-GGUF:Q5_K_M
alias = Qwen3-Coder-Next
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 262144
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 262144
no-kv-offload = 0

[ggml-org/gemma-3-1b-it-GGUF]
jinja = 1
ctx-size = 8192
hf-repo = ggml-org/gemma-3-1b-it-GGUF
alias = Gemma 3
n-gpu-layers = -1
#n-batch = 512
#n-ctx = 8192
